SYSprint("SECURE BOOT SYSTEM","STARTING SECURE BOOT")
if os.getenv("OS_SECURE_BOOT_KEY") == os.getenv("BIOS_MAIN_OS_SECURE_BOOT_KEY") then
	SYSprint("SECURE BOOT SYSTEM","KEY VALIDADATED")
	SYSprint("SECURE BOOT SYSTEM","WAITING FOR CORE_CONFIG_FILES")
	require("CORE/CORE_CONFIG_FILES/BOOT_CONFIG")
	SYSprint("SECURE BOOT SYSTEM","SECURE BOOT DONE")
	debug = nil

	SYSprint("SECURE BOOT SYSTEM","CLEARING CONSOLE IF CLR_ON_BOOT_DONE TRUE")
	if CLR_ON_BOOT_DONE then
		os.execute("clear")
	end
	require("CORE/CORE_OS/MAIN_OS")
else
	SYSprint("SECURE BOOT SYSTEM","ERROR: SBK IS NOT APPROVED")
	SYSprint("SECURE BOOT SYSTEM","SECURE BOOT FAILED")
	C_ERROR("53424b5f49535f4e4f545f415050524f564544")
	end
